### PR TITLE
add repr

### PR DESCRIPTION
**Pull request by garasubo**
Just make sure VolatileCell<T> has the same ABI as T

Ref: #5

### CODE REVIEW

**Comment by RReverser** [comment]
I was about to make the same PR. This is useful for FFI usecases. @japaric any chance of this getting merged?

**Comment by RReverser** [comment]
Or... cc @korken89 I guess?

**Review by korken89 — APPROVED** [review]
With the aim of being like `core::cell::Cell` (which has the transparent attribute) but with volatile accesses, this LGTM.

**Comment by RReverser** [comment]
@korken89 Thanks!

**Pull request merged**
